config/routes.rb
Rails.application.routes.draw do
	root to: 'auth#login'
	
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	get '/conduit/search_task', to: 'conduit#search_task'
  	get '/conduit/search_user', to: 'conduit#search_user'
  	get '/conduit/search_project', to: 'conduit#search_project'
	get '/conduit/get_all_events', to: 'conduit#get_all_events'
	get '/schedule', to: 'schedule#index'
  	get '/schedule/daily', to: 'schedule#daily'
	post '/schedule/save_schedule', to: 'schedule#save_schedule'
	get '/dashboard', to: 'dashboard#daily'
	get '/events/realization/:id', to: 'events#set_realization'
	get '/dashboard/progress', to: 'dashboard#progress'
	get '/dashboard/retrieve_task', to: 'dashboard#retrieve_task'
	get '/dashboard/retrieve_time', to: 'dashboard#retrieve_time'
	get '/search', to: 'search#search'
	get '/login', to: 'auth#login', as: :login
	get '/logout', to: 'auth#logout', as: :logout
	get '/dashboard/start_task/:task_id', to: 'dashboard#start_task'
	get '/dashboard/start_event/:event_id', to: 'dashboard#start_event'
	get '/dashboard/end_running_task', to: 'dashboard#end_running_task'
	post '/dashboard/update_end_time', to: 'dashboard#update_end_time'
	post '/settings/set_focus', to: 'settings#set_focus'
	get '/settings/retrieve_focus', to: 'settings#retrieve_focus'
	get '/settings', to: 'settings#setting'

	resources :events
	resources :settings
	resources :realizations
    resources :custom_tasks
    resources :customs
end

app/models/custom_task.rb
class CustomTask < ActiveRecord::Base
	validates :title, presence: true
end

app/controllers/custom_tasks_controller.rb
class CustomTasksController < ApplicationController
  before_action :set_custom_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!

  # GET /custom_tasks
  # GET /custom_tasks.json
  def index
    @custom_tasks = CustomTask.all
  end

  # GET /custom_tasks/1
  # GET /custom_tasks/1.json
  def show
    @custom_tasks = CustomTask.find(params[:id])
    render action: 'index'
  end

  # GET /custom_tasks/new
  def new
    @custom_task = CustomTask.new
  end

  # GET /custom_tasks/1/edit
  def edit
  end

  # POST /custom_tasks
  # POST /custom_tasks.json
  def create
    @custom_task = CustomTask.new(custom_task_params)
    respond_to do |format|
      if @custom_task.save
        format.html { redirect_to schedule_url, notice: 'Custom task was successfully created.' }
        format.json { render :show, status: :created, location: @custom_task }
      else
        format.html { render :new }
        format.json { render json: @custom_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_tasks/1
  # PATCH/PUT /custom_tasks/1.json
  def update

  end

  # DELETE /custom_tasks/1
  # DELETE /custom_tasks/1.json
  def destroy
    @custom_task.destroy
    respond_to do |format|
      format.html { redirect_to schedule_url, notice: 'Custom task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_task
      @custom_task = CustomTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_task_params
      params.require(:custom_task).permit(:title, :color)
    end
end

app/helpers/custom_tasks_helper.rb
module CustomTasksHelper
end

app/views/custom_tasks/_form.html.erb
<%= simple_form_for(@custom_task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :color %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/custom_tasks/_index.html.erb
            <div class="box-header with-border">
                <h4 class="box-title pull-right">Created Custom Tasks</h4>
            </div>
            <div class="box-body">
          <!-- the events -->
                <div id="external-events" class="external-events-other">
                    <% customtasks = CustomTask.all %>
                    <% customtasks.each do |ct| %>
                        <div class="external-event <%= ct.color %>">
                            <%= ct.title %>
                            <div class="pull-right">
                                <%= link_to "x", ct, method: :delete %>
                            </div>
                        </div>
                    <% end %>
                    <% if customtasks.size == 0 %>
                        No custom activity yet.
                    <% end %>
                </div>
            </div>
        <!-- /.box-body -->

            <div class="box-header with-border">
                <h3 class="box-title pull-right">Create new Custom Task</h3>
            </div>
            <div class="box-body">
          <!-- /btn-group -->

                <div class="input-group" id="customtask-form">
                    <%= simple_form_for CustomTask.new, :id => 'custom-form', remote: true do |f| %>

                        <%= f.text_field :title, placeholder: "custom task title...", required: true %>
                        <%= f.submit "add!", class: 'btn customtask-button pull-right' %>
                    <% end %>
            <!-- /btn-group -->
                </div>
          <!-- /input-group -->
            </div>

            <script type="text/javascript">
              $('.simple_form').on('ajax:error',function(e, xhr, status, error) {
                  if(error == "Not Acceptable") {
                      var json_response = JSON.parse(xhr.responseText);
                      $('#report-error-code').html("(" + json_response['error_code'] + ")");
                      $('#report-error-message').html(json_response['error_message']);
                      $('.report-message').slideDown('fast');
                  } else {
                      $('#report-error-code').html("(1000)");
                      $('#report-error-message').html("Unknown error! please try again");
                      $('.report-message').slideUp('fast');
                  }
              }).on('ajax:beforeSend', function(xhr, settings) {
                  $('.loading-screen').show();
              }).on('ajax:complete', function(xhr, status) {
                  $('.loading-screen').hide();
                  if($('#custom_task_title').val().length > 0) {
                    location.reload();
                  } else {
                    $('#report-error-code').html("(4001)");
                    $('#report-error-message').html("Title required!");
                    $('.report-message').slideDown('fast');
                  }
              });
            </script>

app/views/custom_tasks/edit.html.erb
<h1>Editing Custom Task</h1>

<%= render 'form', custom_task: @custom_task %>

<%= link_to 'Show', @custom_task %> |
<%= link_to 'Back', custom_tasks_path %>

app/views/custom_tasks/index.html.erb
            <div class="box-header with-border">
                <h4 class="box-title pull-right">Created Custom Tasks</h4>
            </div>
            <div class="box-body">
          <!-- the events -->
                <div id="external-events" class="external-events-other">
                    <% customtasks = CustomTask.all %>
                    <% customtasks.each do |ct| %>
                        <div class="external-event <%= ct.color %>">
                            <%= ct.title %>
                            <div class="pull-right" id="delete-button">
                                <%= link_to "x", ct, {method: :delete}, {:style=>'color:white;'}%>
                            </div>
                        </div>
                    <% end %>
                    <% if customtasks.size == 0 %>
                        No custom activity yet.
                    <% end %>
                </div>
            </div>
        <!-- /.box-body -->

            <div class="box-header with-border">
                <h3 class="box-title pull-right">Create new Custom Task</h3>
            </div>
            <div class="box-body">
                <div class="btn-group" style="width: 100%; margin-bottom: 10px;">
                    <ul class="fc-color-picker" id="color-chooser">
                        <li><a class="text-maroon" href="#"><i class="fa fa-square"></i></a></li>
                        <li><a class="text-red" href="#"><i class="fa fa-square"></i></a></li>
                        <li><a class="text-orange" href="#"><i class="fa fa-square"></i></a></li>
                        <li><a class="text-yellow" href="#"><i class="fa fa-square"></i></a></li>
                        <li><a class="text-olive" href="#"><i class="fa fa-square"></i></a></li>
                        <li><a class="text-blue" href="#"><i class="fa fa-square"></i></a></li>
                        <li><a class="text-light-blue" href="#"><i class="fa fa-square"></i></a></li>
                        <li><a class="text-aqua" href="#"><i class="fa fa-square"></i></a></li>
                        <li><a class="text-teal" href="#"><i class="fa fa-square"></i></a></li>
                        <li><a class="text-purple" href="#"><i class="fa fa-square"></i></a></li>
                        <li><a class="text-pink" href="#"><i class="fa fa-square"></i></a></li>
                        <li><a class="text-navy" href="#"><i class="fa fa-square"></i></a></li>
                    </ul>
                </div>
          <!-- /btn-group -->
                <div class="input-group" id="customtask-form">
                     <%= form_for(CustomTask.new) do |f| %>
                        <%= f.text_field :title %>
                          <%= f.submit %>
                    <% end %>
            <!-- /btn-group -->
                </div>
          <!-- /input-group -->
            </div>

app/views/custom_tasks/new.html.erb
<h1>New Custom Task</h1>

<%= render 'form', custom_task: @custom_task %>

<%= link_to 'Back', custom_tasks_path %>

app/views/custom_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @custom_task.title %>
</p>

<p>
  <strong>Color:</strong>
  <%= @custom_task.color %>
</p>

<%= link_to 'Edit', edit_custom_task_path(@custom_task) %> |
<%= link_to 'Back', custom_tasks_path %>